### ISSUE TITLE
Sphinx vs Docusaurus

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/software-development-handbook#40]
For Python projects, Docusaurus has no feature to extract docstrings, so that's a no-go.

Otherwise, we have:

* Standards documentation
* Handbooks
* Deploy repository

For standards documentation, we have a lot of extensions to be able to use the schema and codelist files as single sources of truth, which would need to be re-created for Docusaurus. This likely exceeds any savings from a switch.

If the standards documentation are not switching, then the standards handbook needs to stay on Sphinx, to be able to show usage of the Sphinx extensions.

That leaves only the software handbook and deploy repository, for which it would be unnecessarily complicated to use a different documentation tool.

**Comment by deezed420** [comment]
Sweet
