### ISSUE TITLE
SQL: Add style guide

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/software-development-handbook#43]
e.g. https://kingfisher-summarize.readthedocs.io/en/latest/develop/sql.html#format-sql-files

**Comment by duncandewhurst** [comment]
I'm happy with pg_format

**Comment by jpmckinney** [comment]
As part of this issue, apply it to `miscellaneous-private-scripts`. (kingfisher-summarize already uses `pg_format`. There are only a couple SQL files in `deploy` in `pelican-backend`.)

**Comment by jpmckinney** [comment]
Applied to miscellaneous-private-scripts, deploy and pelican-backend.
