### ISSUE TITLE
A page about Python Testing?

### ISSUE THREAD

**Issue by odscjames** [open-contracting/software-development-handbook#6]
Thinks like:

* isort
* flake8
* the standard test scripts
* per repo tests scripts, pytest, etc
* Use of Github Actions
* the I18N strings tests

**Comment by jpmckinney** [comment]
flake8 and isort are performed by standard-maintenance-scripts in all repos (or should be), and those are mentioned here https://ocp-software-handbook.readthedocs.io/en/latest/python/code.html#style-guide

GitHub Actions is mentioned as a preference here: https://ocp-software-handbook.readthedocs.io/en/latest/general/preferences.html

For per-repo tests, pytest is mentioned as preferred: https://ocp-software-handbook.readthedocs.io/en/latest/python/code.html#preferred-packages

Can you add docs for "I18N strings tests"?

We could have one page that brings all these together, but it'd be helpful to know what questions that page is intended to answer first.

**Comment by odscjames** [comment]
> but it'd be helpful to know what questions that page is intended to answer first.

"As a new developer on OCDS Software, what tests and professional practices should I be using on my code? How do I work with CI to make my work better?"

"As a current developer on OCDS Software, I would like a reference of how to run tests (inc Flake8 etc) locally before pushing to CI - because doing so is often faster and sometimes essential to track down problems" 

Linking out to existing places is fine - thanks for those links.
