### ISSUE TITLE
Add Credere to list of products 

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/software-development-handbook#98]
https://ocp-software-handbook.readthedocs.io/en/latest/roadmap/index.html

We also created collect-generic recently, but I don’t think we’re treating it as a main product.

Please add the repositories and services to https://docs.google.com/spreadsheets/d/1MMqid2qDto_9-MLD_qDppsqkQy_6OP-Uo-9dCgoxjSg/edit (I need to make some updates for 2023)

**Comment by yolile** [comment]
> We also created collect-generic recently, but I don’t think we’re treating it as a main product.

I guess I could also add that one as "alpha" "It is an experimental tool that is not yet regularly used (e.g. ocds-pdf);"

**Comment by yolile** [comment]
> https://ocp-software-handbook.readthedocs.io/en/latest/roadmap/index.html

Ah, I see that the registry is also not there, should I add it as part of the same PR?

**Comment by jpmckinney** [comment]
Yes, please!

**Comment by jpmckinney** [comment]
I split the families into groups: https://ocp-software-handbook.readthedocs.io/en/latest/roadmap/index.html
